# Generated by Django 4.2 on 2023-05-06 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        
    ]

    operations = [
        migrations.CreateModel(
            name="araclar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("description", models.TextField()),
                ("image", models.ImageField(default="", upload_to="images")),
                ("date", models.DateField(auto_now=True)),
                ("isActive", models.BooleanField(default=False)),
                ("isHome", models.BooleanField(default=False)),
                ("slug", models.SlugField(blank=True, default="", unique=True)),
            ],
        ),
        migrations.RenameModel(
            old_name="Category",
            new_name="marka",
        ),
        migrations.DeleteModel(
            name="Course",
        ),
        migrations.AddField(
            model_name="araclar",
            name="marka",
            field=models.ManyToManyField(to="araclar.marka"),
        ),
    ]
